Jack_birthday=("21st July")
Simon_birthday=("10th January")
Ali_birthday=("19th November")
Conor_birthday=("2nd August")
Jason_birthday=("27th March")
print("Jack's birthday is on",Jack_birthday)
print("Simon's birthday is on",Simon_birthday)
print("Ali's birthday is on",Ali_birthday)
print("Conor's birthday is on",Conor_birthday)
print("Jason's birthday is on",Jason_birthday)